version: 2.1
jobs:
  build:
    working_directory: ~/curriculummapper
    docker:
      - image: cimg/python:3.8.4

    steps:
      # step 1: obtain repo from GitHub
      - checkout
      # step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv curriculummappervenv
            . curriculummappervenv/bin/activate
            pip install -r requirements.txt
            python -m build
            pip install dist/*
      # step 3: run linter and tests
      - run:
          name: run linter and tests
          command: |
            . curriculum_mapper_venv/bin/activate
            flake8 --exclude=curriculum_mapper_venv* --statistics
            pytest -v --cov
