version: 2.1
jobs:
  build:
    working_directory: ~/curriculum-mapper
    docker:
      - image: circleci/python:3.8
    steps:
      # step 1: obtain repo from GitHub
      - checkout
      # step 2: create virtual env and install dependencies
      - run: 
          name: install dependencies
          command: |
            python3 -m venv curriculum-mapper-venv
            . curriculum-mapper-venv/bin/activate
            pip install -r requirements.txt
      # step 3: run linter and tests
      - run:
          name: run linter and tests
          command: |
            . curriculum-mapper-venv/bin/activate
            flake8 --exclude=curriculum-mapper-venv* --statistics
            pytest -v --cov
