version: 2.1
jobs:
  build:
    working_directory: ~/curriculummapper
    docker:
      - image: cimg/python:3.9.11

    parallelism: 4

    steps:
      # step 1: obtain repo from GitHub
      - checkout
      # step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv CMvenv
            . CMvenv/bin/activate
            pip install -r requirements.txt
      # step 3: run linter and tests
      - run:
          name: run linter and tests
          command: |
            . CMvenv/bin/activate
            flake8 --exclude=CMvenv/* --statistics
            pytest -v
